"""Telemetry generator: simulates 4 studio services, exposes Prometheus metrics,
an in-memory log/trace feed, and failure injection endpoints. Runs a background
loop pushing fresh samples every ~5s."""
import asyncio
import contextlib
from fastapi import FastAPI, Response
from fastapi.middleware.cors import CORSMiddleware

from .services import STATE, SERVICES
from .metrics import record_sample, render_metrics
from .logs import push_log, recent_logs
from .traces import emit_span, recent_spans
from .shots import SHOT_MANAGER

app = FastAPI(title="Studio Sentinel — Telemetry Generator")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])


async def _tick_loop():
    while True:
        failing_svcs = {name for name, svc in STATE.items() if svc.failing}
        SHOT_MANAGER.tick(failing_svcs)

        for svc in STATE.values():
            sample = svc.sample()
            record_sample(sample)
            push_log(svc.name, sample["log_line"])
            emit_span(svc.name, sample["latency_p95_ms"], error=sample["error_rate_pct"] > 5)
        await asyncio.sleep(5)


@app.on_event("startup")
async def _startup():
    app.state.task = asyncio.create_task(_tick_loop())


@app.on_event("shutdown")
async def _shutdown():
    app.state.task.cancel()
    with contextlib.suppress(asyncio.CancelledError):
        await app.state.task


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/metrics")
def metrics():
    return Response(content=render_metrics(), media_type="text/plain")


@app.get("/shots")
def get_shots():
    """Live Hollywood studio shot queue generated by the generator."""
    return {"shots": SHOT_MANAGER.get_all()}


@app.get("/status")
def status():
    """Convenience endpoint for DIRECT_MODE — everything an agent would otherwise
    have to gather via separate PromQL/LogQL/Tempo MCP calls, in one shot."""
    out = {}
    for name, svc in STATE.items():
        latest = svc.sample()
        out[name] = {
            **latest,
            "recent_logs": recent_logs(name),
            "recent_spans": recent_spans(name),
            "queue_trend_per_min": svc.queue_trend_per_min(),
            "failing": svc.failing,
        }
    return out


@app.post("/inject-failure")
def inject_failure(service: str = "render"):
    if service not in STATE:
        return Response(status_code=404, content=f"unknown service {service}")
    STATE[service].failing = True
    return {"service": service, "failing": True}


@app.post("/clear-failure")
def clear_failure(service: str = "render"):
    if service not in STATE:
        return Response(status_code=404, content=f"unknown service {service}")
    STATE[service].failing = False
    return {"service": service, "failing": False}


@app.post("/restart")
def restart(service: str = "render"):
    if service not in STATE:
        return Response(status_code=404, content=f"unknown service {service}")
    STATE[service].failing = False
    STATE[service].queue_history.clear()
    return {"service": service, "restarted": True, "failing": False}


@app.get("/services")
def list_services():
    return {"services": SERVICES}


@app.get("/scenarios")
def list_scenarios():
    from .services import FAILURE_PROFILE
    return {
        "scenarios": [
            {
                "id": profile["scenario_id"],
                "service": svc,
                "title": profile["scenario_title"],
                "narrative": profile["narrative"],
            }
            for svc, profile in FAILURE_PROFILE.items()
        ]
    }


@app.post("/inject-scenario")
def inject_scenario(scenario_id: str):
    from .services import FAILURE_PROFILE
    for svc, profile in FAILURE_PROFILE.items():
        if profile.get("scenario_id") == scenario_id:
            STATE[svc].failing = True
            return {"service": svc, "scenario_id": scenario_id, "failing": True}
    return Response(status_code=404, content=f"unknown scenario {scenario_id}")

